Parameters:
  StageName:
    Type: String
  AppName:
    Type: String

Resources:
  # This is a secret that has its value hardcoded into the template (NOT RECOMMENDED)
  WalletMnemonicSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${AppName}-wallet-mnemonic-${StageName}"
      SecretString: '{"mnemonic":"test test test test test test test test test test test junk","password":"secret-password"}'
