Parameters:
  AppName:
    Description: The name of the application
    Type: String

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketArn:
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name: !Sub ${AppName}-S3DeploymentBucketArn
  S3BucketName:
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub ${AppName}-S3DeploymentBucketName
