AWSTemplateFormatVersion: '2010-09-09'
Description: DocumentDB Free Tier Compatible Setup

Parameters:
  AppName:
    Description: The app of the stack
    Type: String

Resources:
  # DocumentDB Subnet Group using the default VPC subnets
  DBSubnetGroup:
    Type: AWS::DocDB::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for DocumentDB cluster
      SubnetIds: !Split
        - ","
        - !ImportValue
          'Fn::Sub': '${AppName}-PrivateSubnetIds'

  # DocumentDB Cluster
  DocDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      EngineVersion: '4.0.0'
      MasterUsername: masterAdmin
      MasterUserPassword: SecurePassword123
      DBClusterIdentifier: !Sub ${AppName}-DocumentDBCluster
      VpcSecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${AppName}-SecurityGroupId'
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 1
      PreferredBackupWindow: 03:00-06:00
      PreferredMaintenanceWindow: Sun:06:00-Sun:07:00
      StorageEncrypted: true

  # DocumentDB Instance
  DocDBInstance:
    Type: AWS::DocDB::DBInstance
    Properties:
      # DBInstanceClass: db.r5.large  # Instance class suited for production workloads
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref DocDBCluster
      DBInstanceIdentifier: !Sub ${AppName}-DocumentDBInstance
      PreferredMaintenanceWindow: Sun:06:00-Sun:07:00  # Maintenance window
      AutoMinorVersionUpgrade: true  # Enable automatic minor version upgrades

Outputs:
  DocumentDBEndpoint:
    Description: Endpoint for connecting to the DocumentDB cluster
    Value: !GetAtt DocDBCluster.Endpoint
    Export:
      Name: !Sub ${AppName}-DocumentDBEndpoint
