AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Default: "dev"
    Description: "The name of the API stage"
  AppName:
    Type: String
    Description: "The name of the application"

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        AllowHeaders: ['Content-Type', 'Authorization']
        AllowOrigins: ['*']
      StageName: !Ref StageName

  AdminLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apps/admin/index.handler
      Runtime: nodejs18.x
      CodeUri: ../../../backend/src
      MemorySize: 128
      Timeout: 20
      VpcConfig:
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': '${AppName}-SecurityGroupId'
        SubnetIds: !Split
          - ","
          - !ImportValue
            'Fn::Sub': '${AppName}-PrivateSubnetIds'
          # - !Select 
          #   - 0
          #   - !Split 
          #     - ","
          #     - !ImportValue 
          #       'Fn::Sub': '${AppName}-SubnetIds'
          # - !Select 
          #   - 1
          #   - !Split 
          #     - ","
          #     - !ImportValue 
          #       'Fn::Sub': '${AppName}-SubnetIds'
      Environment:
        Variables:
          STAGE: !Ref StageName
          DOCUMENTDB_ENDPOINT: !ImportValue 
            'Fn::Sub': '${AppName}-DocumentDBEndpoint'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - "secretsmanager:GetSecretValue"
              Resource: "*"

      Events:
        ApiEventAdmin:
          Type: HttpApi
          Properties:
            Path: /admin
            Method: ANY
            ApiId: !Ref HttpApi
        ApiEventAdminProxy:
          Type: HttpApi
          Properties:
            Path: /admin/{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi

  CustomerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apps/customer/index.handler
      Runtime: nodejs18.x
      CodeUri: ../../../backend/src
      MemorySize: 128
      Timeout: 20
      VpcConfig:
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': '${AppName}-SecurityGroupId'
        SubnetIds: !Split
          - ","
          - !ImportValue
            'Fn::Sub': '${AppName}-PrivateSubnetIds'
        # SecurityGroupIds: 
        #   - !ImportValue 
        #     'Fn::Sub': '${AppName}-LambdaSecurityGroupId'
        # SubnetIds:
        #   - !Select 
        #     - 0
        #     - !Split 
        #       - ","
        #       - !ImportValue 
        #         'Fn::Sub': '${AppName}-SubnetIds'
        #   - !Select 
        #     - 1
        #     - !Split 
        #       - ","
        #       - !ImportValue 
        #         'Fn::Sub': '${AppName}-SubnetIds'
      Environment:
        Variables:
          STAGE: !Ref StageName
          DOCUMENTDB_ENDPOINT: !ImportValue 
            'Fn::Sub': '${AppName}-DocumentDBEndpoint'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - "secretsmanager:GetSecretValue"
              Resource: "*"
      Events:
        ApiEventAdmin:
          Type: HttpApi
          Properties:
            Path: /customer
            Method: ANY
            ApiId: !Ref HttpApi
        ApiEventAdminProxy:
          Type: HttpApi
          Properties:
            Path: /customer/{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi

Outputs:
  ApiGatewayAdminInvokeURL:
    Description: "Invoke URL for the API Gateway"
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/admin'

  AdminLambdaFunctionArn:
    Description: "ARN of the deployed Lambda function"
    Value: !GetAtt AdminLambdaFunction.Arn

  ApiGatewayCustomerInvokeURL:
    Description: "Invoke URL for the API Gateway"
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/customer'

  CustomerLambdaFunctionArn:
    Description: "ARN of the deployed Lambda function"
    Value: !GetAtt CustomerLambdaFunction.Arn
