AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Default: "dev"
    Description: "The name of the API stage"
  AppName:
    Type: String
    Description: "The name of the application"

Resources:
  BastionHostLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: bastion-host
      MemorySize: 128
      Timeout: 30
      VpcConfig:
        SecurityGroupIds: 
          - !ImportValue 
            'Fn::Sub': '${AppName}-SecurityGroupId'
        SubnetIds: !Split
          - ","
          - !ImportValue
            'Fn::Sub': '${AppName}-PrivateSubnetIds'
      Environment:
        Variables:
          STAGE: !Ref StageName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - "ssm:SendCommand"
                - "ssm:GetCommandInvocation"
              Resource: "*"

# Outputs:
#   AdminLambdaFunctionArn:
#     Description: "ARN of the deployed Lambda function"
#     Value: !GetAtt AdminLambdaFunction.Arn
